version: 2
jobs:
  echo_1:
    machine: true
    steps:
    - run: echo $CIRCLE_SHA1
    - run: echo $CIRCLE_TAG
    - run: echo "Should run this"
  echo_2:
    machine: true
    steps:
    - run: echo $CIRCLE_SHA1
    - run: echo $CIRCLE_TAG
    - run: echo "Please don't echo"
workflows:
  version: 2
  flow:
    jobs:
    - echo_1
    - echo_2:
        requires:
        - echo_1
        filters:
          branches:
            ignore: /.*/
          tags:
            only: v0.0.5
