version: 2
jobs:
  echo:
    machine: true
    steps:
      - run: echo "Please don't echo..."
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - echo:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
