version: 2
jobs:
  echo_1:
    machine: true
    steps:
    - run: echo "Should run this (${CIRCLE_TAG})"
  echo_2:
    machine: true
    steps:
    - run: echo "Please don't echo... (${CIRCLE_TAG})"
workflows:
  version: 2
  flow:
    jobs:
    - echo_1
    - echo_2:
        requires:
        - echo_1
        filters:
          branches:
            ignore: /.*/
          tags:
            # only: /^v[0-9]+(\.[0-9]+)*/
            only: /^v*/