version: 2
jobs:
  echo_1:
    machine: true
    steps:
    - run: echo "Should run this ($CIRCLE_TAG $CIRCLE_SHA1)"
  echo_2:
    machine: true
    steps:
    - run: echo "Please don't echo... ($CIRCLE_TAG $CIRCLE_SHA1)"
workflows:
  version: 2
  flow:
    jobs:
    - echo_1
    - echo_2:
        requires:
        - echo_1
        filters:
          branches:
            only: master
          tags:
            ignore: v0.0.1
# test