version: 2
jobs:
  echo_1:
    machine: true
    steps:
    - run: echo "Should run this"
  echo_2:
    machine: true
    steps:
    - run: echo "Please don't echo..."
workflows:
  version: 2
  flow:
    jobs:
    - echo_1
    - echo_2:
        requires:
        - echo_1
        filters:
          tags:
            ignore: /^v[0-9]+(\.[0-9]+)*/
